# Fixes to JSBSim that flightsim carries.
#
# The submodule stays exactly as upstream ships it. Each fixed file is
# generated into the build tree - the upstream source with the edits below,
# each marked "flightsim patch" in the code - and compiled in place of the
# original (JSBSim is LGPL-2.1; see THIRD_PARTY_NOTICES.md). Every edit names
# the exact text it replaces: if upstream JSBSim no longer has it, configuring
# stops, so the fix is reviewed rather than silently lost.

set(_fsim_jsbsim_patched ${CMAKE_BINARY_DIR}/third_party/jsbsim-patched)

# Replace the one occurrence of the text in variable `old_var` with the text in
# `new_var`, inside variable `text_var`.
function(_fsim_jsbsim_edit text_var old_var new_var file what)
    string(FIND "${${text_var}}" "${${old_var}}" _at)
    if(_at EQUAL -1)
        message(FATAL_ERROR "JSBSim fix '${what}' no longer applies to ${file}: upstream changed it. "
                            "Review cmake/JsbsimPatches.cmake.")
    endif()
    string(REPLACE "${${old_var}}" "${${new_var}}" _text "${${text_var}}")
    set(${text_var} "${_text}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------------------
# models/FGLGear.cpp: a wheel on its side.
#
# A wheel's (BOGEY) strut is projected on the ground normal three times: its
# compression and compression speed are divided by the cosine of the strut's
# angle to the normal, and so is the ground force. As the strut turns towards
# the ground plane - a wheel meeting the ground sideways, as in a cartwheel -
# the force grows as 1/cos^2 without bound (0/0, NaN, with the strut parallel
# to the ground), and the aircraft is thrown back into the air or blows up:
# the stock c172x reached 9600 m/s. The projection is bounded at 45 degrees,
# so nothing changes while a strut is within 45 degrees of the ground normal.
# ---------------------------------------------------------------------------
set(_src ${FSIM_JSBSIM_SOURCE_DIR}/src/models/FGLGear.cpp)
file(READ ${_src} _text)
string(REPLACE "\r\n" "\n" _text "${_text}")

set(_old [=[namespace JSBSim {
]=])
set(_new [=[namespace JSBSim {

// flightsim patch (cmake/JsbsimPatches.cmake): the smallest projection of a
// wheel's strut on the ground normal used to turn its compression and force
// into the ground's frame - cos(45 deg). Below it, dividing by the projection
// made the ground force grow without bound as a wheel met the ground sideways.
static const double kMinStrutProjection = 0.70710678118654752;
]=])
_fsim_jsbsim_edit(_text _old _new ${_src} "the bound")

set(_old [=[      LGearProj = -(mTGear.Transposed() * vGroundNormal)(eZ);
]=])
set(_new [=[      LGearProj = -(mTGear.Transposed() * vGroundNormal)(eZ);
      // flightsim patch: bounded, see kMinStrutProjection
      if (LGearProj > 0.0) LGearProj = max(LGearProj, kMinStrutProjection);
]=])
_fsim_jsbsim_edit(_text _old _new ${_src} "compression")

set(_old [=[        if (eContactType == ctBOGEY)
          compressSpeed /= LGearProj;
]=])
set(_new [=[        if (eContactType == ctBOGEY) // flightsim patch: no 0/0 with the strut along the ground
          compressSpeed = LGearProj > 0.0 ? compressSpeed / LGearProj : 0.0;
]=])
_fsim_jsbsim_edit(_text _old _new ${_src} "compression speed")

set(_old [=[    vFn(eZ) = StrutForce / (mTGear.Transposed()*vGroundNormal)(eZ);
]=])
set(_new [=[    // flightsim patch: the projection bounded as for the compression; a
    // strut pointing away from the ground pushes on nothing
    {
      const double proj = (mTGear.Transposed()*vGroundNormal)(eZ);
      vFn(eZ) = proj < 0.0 ? StrutForce / min(proj, -kMinStrutProjection) : 0.0;
    }
]=])
_fsim_jsbsim_edit(_text _old _new ${_src} "ground force")

set(_dst ${_fsim_jsbsim_patched}/models/FGLGear.cpp)
file(WRITE ${_dst}.new "// Generated by flightsim from JSBSim's src/models/FGLGear.cpp with the fixes\n"
                       "// in cmake/JsbsimPatches.cmake (marked \"flightsim patch\"). Do not edit.\n${_text}")
configure_file(${_dst}.new ${_dst} COPYONLY) # rewritten only when it changes: no needless rebuilds
file(REMOVE ${_dst}.new)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_src})

get_target_property(_srcs Models SOURCES)
list(TRANSFORM _srcs REPLACE "(^|.*/)FGLGear\\.cpp$" "${_dst}")
set_property(TARGET Models PROPERTY SOURCES ${_srcs})
target_include_directories(Models PRIVATE ${FSIM_JSBSIM_SOURCE_DIR}/src/models) # its #include "FGLGear.h"

# Write the text of variable `text_var`, JSBSim's src/<rel> with fixes, into
# the build tree; with a target, compile it in place of the original.
function(_fsim_jsbsim_write rel text_var target)
    set(_dst ${_fsim_jsbsim_patched}/${rel})
    file(WRITE ${_dst}.new "// Generated by flightsim from JSBSim's src/${rel} with the fixes\n"
                           "// in cmake/JsbsimPatches.cmake (marked \"flightsim patch\"). Do not edit.\n${${text_var}}")
    configure_file(${_dst}.new ${_dst} COPYONLY)
    file(REMOVE ${_dst}.new)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${FSIM_JSBSIM_SOURCE_DIR}/src/${rel})
    if(target)
        get_filename_component(_name ${rel} NAME)
        string(REPLACE "." "\\." _name_re ${_name})
        get_target_property(_srcs ${target} SOURCES)
        list(TRANSFORM _srcs REPLACE "(^|.*/)${_name_re}$" "${_dst}")
        set_property(TARGET ${target} PROPERTY SOURCES ${_srcs})
    endif()
endfunction()

function(_fsim_jsbsim_read rel text_var)
    file(READ ${FSIM_JSBSIM_SOURCE_DIR}/src/${rel} _t)
    string(REPLACE "\r\n" "\n" _t "${_t}")
    set(${text_var} "${_t}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------------------
# models/propulsion/FGRotor.h and FGRotor.cpp: a rotor after a reset, and the
# classical rotor forces.
#
# 1. A reset started a rotor from what the previous run left: FGRotor has no
#    ResetToIC, so its inflow, its ground-height filter and a transmission's
#    rpm carried over, and what a reset did depended on what ran before it.
#    And a start began the inflow at lambda = -0.001, whose first update
#    divides the thrust by 2|lambda|: a UH-1H's tail rotor reached C_T = -0.17
#    in it. Now a reset restarts a rotor as a load does (at rest if a
#    transmission drives it), and the first calculation after either converges
#    the inflow, and the ground-height filter, at the state it starts from.
# 2. <model> classical </model> in a rotor's file (default: heffley, upstream's
#    forms) computes the in-plane forces and the torque from the classical
#    blade-element expressions NASA TM-73254 flies (Talbot and Corliss 1977,
#    eq. 1-4). Upstream's minimum-complexity forms (thrust times a flapping
#    angle) leave a UH-1H unstable in angle of attack at 60 kt where the
#    classical ones, and its flight records, are stable (docs/rotorcraft.md).
#    In that model the ground effect scales the inflow's steady state
#    (TM-73254 eq. 10a); upstream's scales the inflow state every step, which
#    compounds with the step and the inflow lag.
# Upstream's own rotorcraft (the AH-1S) keep upstream's forces: only the reset
# changes for them. FGEngine.cpp and FGTurboProp.cpp include FGRotor.h, so they
# are compiled from the build tree too, unchanged, against the changed header.
# ---------------------------------------------------------------------------
_fsim_jsbsim_read(models/propulsion/FGRotor.h _text)
set(_old [=[  double Calculate(double EnginePower);
]=])
set(_new [=[  double Calculate(double EnginePower);

  /// flightsim patch (cmake/JsbsimPatches.cmake): restarts the rotor as a
  /// load does; the next calculation converges its inflow.
  void ResetToIC(void) override;
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.h "reset")
set(_old [=[  double v_induced;  // induced velocity, usually positive [ft/s]
]=])
set(_new [=[  double v_induced;  // induced velocity, usually positive [ft/s]

  // flightsim patch: the classical force model (<model> classical </model>),
  // the rates in the wind-control axes its forces use, and a start to converge
  bool ClassicalModel;
  bool FreshStart;
  double p_w, q_w;
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.h "members")
_fsim_jsbsim_write(models/propulsion/FGRotor.h _text "")

_fsim_jsbsim_read(models/propulsion/FGRotor.cpp _text)
set(_old [=[  Type = ttRotor;
]=])
set(_new [=[  Type = ttRotor;
  ClassicalModel = false; // flightsim patch
  FreshStart = true;
  p_w = q_w = 0.0;
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "initial state")
set(_old [=[FGRotor::~FGRotor(){
  if (Transmission) delete Transmission;
  Debug(1);
}
]=])
set(_new [=[FGRotor::~FGRotor(){
  if (Transmission) delete Transmission;
  Debug(1);
}

// flightsim patch (cmake/JsbsimPatches.cmake): a reset restarts the rotor as
// a load does - at rest if a transmission drives it - and the next
// calculation converges its inflow and ground-height filter.
void FGRotor::ResetToIC(void)
{
  FGThruster::ResetToIC();
  FreshStart = true;
  if (!ExternalRPM) {
    RPM = 0.0;
    Transmission->SetEngineRPM(0.0);
    Transmission->SetThrusterRPM(0.0);
  }
}
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "reset")
set(_old [=[  GroundEffectShift = ConfigValueConv(rotor_element, "groundeffectshift", 0.0, "FT");
]=])
set(_new [=[  GroundEffectShift = ConfigValueConv(rotor_element, "groundeffectshift", 0.0, "FT");

  // flightsim patch: the force model - heffley (upstream's) or classical
  if (Element* model_el = rotor_element->FindElement("model")) {
    string model = rotor_element->FindElementValue("model");
    model = to_upper(model);
    if (model == "CLASSICAL") {
      ClassicalModel = true;
    } else if (model != "HEFFLEY") {
      FGXMLLogging log(model_el, LogLevel::ERROR);
      log << "# unknown rotor model: '" << model << "' using heffley.\n";
    }
  }
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "model")
set(_old [=[  ct_t1 = (1.0/4.0*B[4] + 1.0/4.0 * B[2]*mu2) * BladeTwist;
]=])
set(_new [=[  ct_t1 = (1.0/4.0*B[4] + 1.0/4.0 * B[2]*mu2) * BladeTwist;
  if (ClassicalModel) ct_t1 += 0.25*mu*p_w/Omega; // flightsim patch: roll rate's thrust, TM-73254 eq. 1
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "thrust")
set(_old [=[  nu  = flow_scale * ((nu - c0) * exp(-dt/InflowLag) + c0);
]=])
set(_new [=[  if (ClassicalModel) // flightsim patch: the ground effect scales the steady state
    nu = (nu - flow_scale*c0) * exp(-dt/InflowLag) + flow_scale*c0;
  else
    nu  = flow_scale * ((nu - c0) * exp(-dt/InflowLag) + c0);
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "ground effect")
set(_old [=[  J_side = BladeNum * BladeChord * Radius * rho * sqr(Omega*Radius) * cy_over_sigma;
]=])
set(_new [=[  J_side = BladeNum * BladeChord * Radius * rho * sqr(Omega*Radius) * cy_over_sigma;

  // flightsim patch: the classical H and Y forces in the control axes,
  // TM-73254 eq. 2 and 3 (its untwisted blade pitch is the 3/4-radius pitch)
  if (ClassicalModel) {
    const double r1 = BladeNum*BladeChord*Radius*rho*sqr(Omega*Radius) * LiftCurveSlope/2.0;
    const double mu2 = sqr(mu), pw = p_w/Omega, qw = q_w/Omega;
    const double delta = 0.009 + 0.3*sqr(6.0*C_T/(LiftCurveSlope*Solidity));
    H_drag = r1 * ( delta*mu/(2.0*LiftCurveSlope)
                    + a_1*(t075/3.0 + 0.75*lambda*(1.0 - 0.375*mu2) + 0.25*mu*a_1)
                    - 0.5*mu*lambda*t075*(1.0 - 2.0*mu/(3.0*M_PI)) - 0.25*sqr(lambda)*mu
                    - 0.375*lambda*mu2*(1.0 + 3.33*mu) - a0*(b_1/6.0 - 0.25*a0*mu)
                    - qw*(a0/6.0 + mu*b_1/16.0) - pw*(t075/6.0 + 0.5*lambda + mu*a_1/16.0) );
    J_side = r1 * ( a0*(a_1*(1.0/6.0 - mu2) - 1.5*mu*(lambda + 0.5*t075))
                    + b_1*(t075/3.0*(1.0 + 1.5*mu2) + 0.75*lambda + 0.25*mu*a_1)
                    + qw*(t075/6.0 + 0.5*lambda + 7.0/16.0*mu*a_1) - pw*(a0/6.0 - 5.0/16.0*mu*b_1) );
  }
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "in-plane forces")
set(_old [=[                     - (Thrust*lambda + H_drag*mu)*Radius;
]=])
set(_new [=[                     - (Thrust*lambda + H_drag*mu)*Radius;

  // flightsim patch: the classical torque, TM-73254 eq. 4
  if (ClassicalModel) {
    const double t075 = theta_0 + 0.75 * BladeTwist, mu2 = sqr(mu);
    const double r9 = BladeNum*BladeChord*Radius*rho*sqr(Omega*Radius) * LiftCurveSlope/2.0 * Radius;
    Torque = r9 * ( delta_dr*(1.0 + mu2)/(4.0*LiftCurveSlope) - lambda*t075/3.0 - 0.5*sqr(lambda)
                    - (sqr(a_1) + sqr(b_1))/8.0 - 0.5*mu2*(0.5*sqr(a0) + 0.375*sqr(a_1) + sqr(b_1)/8.0)
                    - 0.5*mu*lambda*a_1 + mu*a0*b_1/3.0 );
  }
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "torque")
set(_old [=[    filtered_hagl = damp_hagl.execute(h_agl_ft) + GroundEffectShift;
]=])
set(_new [=[    if (FreshStart) { // flightsim patch: the filter starts at the height
      damp_hagl = Filter(1.0, dt);
      for (int i = 0; i < 4000; ++i) damp_hagl.execute(h_agl_ft);
    }
    filtered_hagl = damp_hagl.execute(h_agl_ft) + GroundEffectShift;
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "height filter")
set(_old [=[  avFus_ca = fus_angvel_body2ca(in.AeroPQR);

  calc_flow_and_thrust(theta_col, vHub_ca(eU), vHub_ca(eW), ge_factor);
]=])
set(_new [=[  avFus_ca = fus_angvel_body2ca(in.AeroPQR);
  p_w = avFus_ca(eP); // flightsim patch
  q_w = avFus_ca(eQ);

  // flightsim patch: a start converges the inflow from a typical rotor's; each
  // update is the lagged one, so its steady state is the one running reaches
  if (FreshStart) {
    FreshStart = false;
    nu = 0.05;
    lambda = vHub_ca(eW)/(Omega*Radius) - nu;
    for (int i = 0; i < 400; ++i)
      calc_flow_and_thrust(theta_col, vHub_ca(eU), vHub_ca(eW), ge_factor);
  }

  calc_flow_and_thrust(theta_col, vHub_ca(eU), vHub_ca(eW), ge_factor);
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "start")
_fsim_jsbsim_write(models/propulsion/FGRotor.cpp _text Propulsion)

foreach(_includer FGEngine.cpp FGTurboProp.cpp)
    _fsim_jsbsim_read(models/propulsion/${_includer} _text)
    _fsim_jsbsim_write(models/propulsion/${_includer} _text Propulsion)
endforeach()
target_include_directories(Propulsion PRIVATE ${FSIM_JSBSIM_SOURCE_DIR}/src/models/propulsion) # their other headers
