# Fixes to JSBSim that flightsim carries.
#
# The submodule stays exactly as upstream ships it. Each fixed file is
# generated into the build tree - the upstream source with the edits below,
# each marked "flightsim patch" in the code - and compiled in place of the
# original (JSBSim is LGPL-2.1; see THIRD_PARTY_NOTICES.md). Every edit names
# the exact text it replaces: if upstream JSBSim no longer has it, configuring
# stops, so the fix is reviewed rather than silently lost.

set(_fsim_jsbsim_patched ${CMAKE_BINARY_DIR}/third_party/jsbsim-patched)

# Replace the one occurrence of the text in variable `old_var` with the text in
# `new_var`, inside variable `text_var`.
function(_fsim_jsbsim_edit text_var old_var new_var file what)
    string(FIND "${${text_var}}" "${${old_var}}" _at)
    if(_at EQUAL -1)
        message(FATAL_ERROR "JSBSim fix '${what}' no longer applies to ${file}: upstream changed it. "
                            "Review cmake/JsbsimPatches.cmake.")
    endif()
    string(REPLACE "${${old_var}}" "${${new_var}}" _text "${${text_var}}")
    set(${text_var} "${_text}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------------------
# models/FGLGear.cpp: a wheel on its side.
#
# A wheel's (BOGEY) strut is projected on the ground normal three times: its
# compression and compression speed are divided by the cosine of the strut's
# angle to the normal, and so is the ground force. As the strut turns towards
# the ground plane - a wheel meeting the ground sideways, as in a cartwheel -
# the force grows as 1/cos^2 without bound (0/0, NaN, with the strut parallel
# to the ground), and the aircraft is thrown back into the air or blows up:
# the stock c172x reached 9600 m/s. The projection is bounded at 45 degrees,
# so nothing changes while a strut is within 45 degrees of the ground normal.
# ---------------------------------------------------------------------------
set(_src ${FSIM_JSBSIM_SOURCE_DIR}/src/models/FGLGear.cpp)
file(READ ${_src} _text)
string(REPLACE "\r\n" "\n" _text "${_text}")

set(_old [=[namespace JSBSim {
]=])
set(_new [=[namespace JSBSim {

// flightsim patch (cmake/JsbsimPatches.cmake): the smallest projection of a
// wheel's strut on the ground normal used to turn its compression and force
// into the ground's frame - cos(45 deg). Below it, dividing by the projection
// made the ground force grow without bound as a wheel met the ground sideways.
static const double kMinStrutProjection = 0.70710678118654752;
]=])
_fsim_jsbsim_edit(_text _old _new ${_src} "the bound")

set(_old [=[      LGearProj = -(mTGear.Transposed() * vGroundNormal)(eZ);
]=])
set(_new [=[      LGearProj = -(mTGear.Transposed() * vGroundNormal)(eZ);
      // flightsim patch: bounded, see kMinStrutProjection
      if (LGearProj > 0.0) LGearProj = max(LGearProj, kMinStrutProjection);
]=])
_fsim_jsbsim_edit(_text _old _new ${_src} "compression")

set(_old [=[        if (eContactType == ctBOGEY)
          compressSpeed /= LGearProj;
]=])
set(_new [=[        if (eContactType == ctBOGEY) // flightsim patch: no 0/0 with the strut along the ground
          compressSpeed = LGearProj > 0.0 ? compressSpeed / LGearProj : 0.0;
]=])
_fsim_jsbsim_edit(_text _old _new ${_src} "compression speed")

set(_old [=[    vFn(eZ) = StrutForce / (mTGear.Transposed()*vGroundNormal)(eZ);
]=])
set(_new [=[    // flightsim patch: the projection bounded as for the compression; a
    // strut pointing away from the ground pushes on nothing
    {
      const double proj = (mTGear.Transposed()*vGroundNormal)(eZ);
      vFn(eZ) = proj < 0.0 ? StrutForce / min(proj, -kMinStrutProjection) : 0.0;
    }
]=])
_fsim_jsbsim_edit(_text _old _new ${_src} "ground force")

set(_dst ${_fsim_jsbsim_patched}/models/FGLGear.cpp)
file(WRITE ${_dst}.new "// Generated by flightsim from JSBSim's src/models/FGLGear.cpp with the fixes\n"
                       "// in cmake/JsbsimPatches.cmake (marked \"flightsim patch\"). Do not edit.\n${_text}")
configure_file(${_dst}.new ${_dst} COPYONLY) # rewritten only when it changes: no needless rebuilds
file(REMOVE ${_dst}.new)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_src})

get_target_property(_srcs Models SOURCES)
list(TRANSFORM _srcs REPLACE "(^|.*/)FGLGear\\.cpp$" "${_dst}")
set_property(TARGET Models PROPERTY SOURCES ${_srcs})
target_include_directories(Models PRIVATE ${FSIM_JSBSIM_SOURCE_DIR}/src/models) # its #include "FGLGear.h"

# Write the text of variable `text_var`, JSBSim's src/<rel> with fixes, into
# the build tree; with a target, compile it in place of the original.
function(_fsim_jsbsim_write rel text_var target)
    set(_dst ${_fsim_jsbsim_patched}/${rel})
    file(WRITE ${_dst}.new "// Generated by flightsim from JSBSim's src/${rel} with the fixes\n"
                           "// in cmake/JsbsimPatches.cmake (marked \"flightsim patch\"). Do not edit.\n${${text_var}}")
    configure_file(${_dst}.new ${_dst} COPYONLY)
    file(REMOVE ${_dst}.new)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${FSIM_JSBSIM_SOURCE_DIR}/src/${rel})
    if(target)
        get_filename_component(_name ${rel} NAME)
        string(REPLACE "." "\\." _name_re ${_name})
        get_target_property(_srcs ${target} SOURCES)
        list(TRANSFORM _srcs REPLACE "(^|.*/)${_name_re}$" "${_dst}")
        set_property(TARGET ${target} PROPERTY SOURCES ${_srcs})
    endif()
endfunction()

function(_fsim_jsbsim_read rel text_var)
    file(READ ${FSIM_JSBSIM_SOURCE_DIR}/src/${rel} _t)
    string(REPLACE "\r\n" "\n" _t "${_t}")
    set(${text_var} "${_t}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------------------
# models/propulsion/FGRotor.h and FGRotor.cpp: a rotor after a reset, and the
# classical rotor forces.
#
# 1. A reset started a rotor from what the previous run left: FGRotor has no
#    ResetToIC, so its inflow, its ground-height filter and a transmission's
#    rpm carried over, and what a reset did depended on what ran before it.
#    And a start began the inflow at lambda = -0.001, whose first update
#    divides the thrust by 2|lambda|: a UH-1H's tail rotor reached C_T = -0.17
#    in it. Now a reset restarts a rotor as a load does (at rest if a
#    transmission drives it), and the first calculation after either converges
#    the inflow, and the ground-height filter, at the state it starts from.
# 2. <model> classical </model> in a rotor's file (default: heffley, upstream's
#    forms) computes the in-plane forces and the torque from the classical
#    blade-element expressions NASA TM-73254 flies (Talbot and Corliss 1977,
#    eq. 1-4). Upstream's minimum-complexity forms (thrust times a flapping
#    angle) leave a UH-1H unstable in angle of attack at 60 kt where the
#    classical ones, and its flight records, are stable (docs/rotorcraft.md).
#    In that model the ground effect scales the inflow's steady state
#    (TM-73254 eq. 10a); upstream's scales the inflow state every step, which
#    compounds with the step and the inflow lag.
# Upstream's own rotorcraft (the AH-1S) keep upstream's forces: only the reset
# changes for them. FGEngine.cpp and FGTurboProp.cpp include FGRotor.h, so they
# are compiled from the build tree too, unchanged, against the changed header.
# ---------------------------------------------------------------------------
_fsim_jsbsim_read(models/propulsion/FGRotor.h _text)
set(_old [=[  double Calculate(double EnginePower);
]=])
set(_new [=[  double Calculate(double EnginePower);

  /// flightsim patch (cmake/JsbsimPatches.cmake): restarts the rotor as a
  /// load does; the next calculation converges its inflow.
  void ResetToIC(void) override;
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.h "reset")
set(_old [=[  double v_induced;  // induced velocity, usually positive [ft/s]
]=])
set(_new [=[  double v_induced;  // induced velocity, usually positive [ft/s]

  // flightsim patch: the classical force model (<model> classical </model>),
  // the rates in the wind-control axes its forces use, and a start to converge
  bool ClassicalModel;
  bool FreshStart;
  double p_w, q_w;
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.h "members")
_fsim_jsbsim_write(models/propulsion/FGRotor.h _text "")

_fsim_jsbsim_read(models/propulsion/FGRotor.cpp _text)
set(_old [=[  Type = ttRotor;
]=])
set(_new [=[  Type = ttRotor;
  ClassicalModel = false; // flightsim patch
  FreshStart = true;
  p_w = q_w = 0.0;
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "initial state")
set(_old [=[FGRotor::~FGRotor(){
  if (Transmission) delete Transmission;
  Debug(1);
}
]=])
set(_new [=[FGRotor::~FGRotor(){
  if (Transmission) delete Transmission;
  Debug(1);
}

// flightsim patch (cmake/JsbsimPatches.cmake): a reset restarts the rotor as
// a load does - at rest if a transmission drives it - and the next
// calculation converges its inflow and ground-height filter.
void FGRotor::ResetToIC(void)
{
  FGThruster::ResetToIC();
  FreshStart = true;
  if (!ExternalRPM) {
    RPM = 0.0;
    Transmission->SetEngineRPM(0.0);
    Transmission->SetThrusterRPM(0.0);
  }
}
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "reset")
set(_old [=[  GroundEffectShift = ConfigValueConv(rotor_element, "groundeffectshift", 0.0, "FT");
]=])
set(_new [=[  GroundEffectShift = ConfigValueConv(rotor_element, "groundeffectshift", 0.0, "FT");

  // flightsim patch: the force model - heffley (upstream's) or classical
  if (Element* model_el = rotor_element->FindElement("model")) {
    string model = rotor_element->FindElementValue("model");
    model = to_upper(model);
    if (model == "CLASSICAL") {
      ClassicalModel = true;
    } else if (model != "HEFFLEY") {
      FGXMLLogging log(model_el, LogLevel::ERROR);
      log << "# unknown rotor model: '" << model << "' using heffley.\n";
    }
  }
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "model")
set(_old [=[  ct_t1 = (1.0/4.0*B[4] + 1.0/4.0 * B[2]*mu2) * BladeTwist;
]=])
set(_new [=[  ct_t1 = (1.0/4.0*B[4] + 1.0/4.0 * B[2]*mu2) * BladeTwist;
  if (ClassicalModel) ct_t1 += 0.25*mu*p_w/Omega; // flightsim patch: roll rate's thrust, TM-73254 eq. 1
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "thrust")
set(_old [=[  nu  = flow_scale * ((nu - c0) * exp(-dt/InflowLag) + c0);
]=])
set(_new [=[  if (ClassicalModel) // flightsim patch: the ground effect scales the steady state
    nu = (nu - flow_scale*c0) * exp(-dt/InflowLag) + flow_scale*c0;
  else
    nu  = flow_scale * ((nu - c0) * exp(-dt/InflowLag) + c0);
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "ground effect")
set(_old [=[  J_side = BladeNum * BladeChord * Radius * rho * sqr(Omega*Radius) * cy_over_sigma;
]=])
set(_new [=[  J_side = BladeNum * BladeChord * Radius * rho * sqr(Omega*Radius) * cy_over_sigma;

  // flightsim patch: the classical H and Y forces in the control axes,
  // TM-73254 eq. 2 and 3 (its untwisted blade pitch is the 3/4-radius pitch)
  if (ClassicalModel) {
    const double r1 = BladeNum*BladeChord*Radius*rho*sqr(Omega*Radius) * LiftCurveSlope/2.0;
    const double mu2 = sqr(mu), pw = p_w/Omega, qw = q_w/Omega;
    const double delta = 0.009 + 0.3*sqr(6.0*C_T/(LiftCurveSlope*Solidity));
    H_drag = r1 * ( delta*mu/(2.0*LiftCurveSlope)
                    + a_1*(t075/3.0 + 0.75*lambda*(1.0 - 0.375*mu2) + 0.25*mu*a_1)
                    - 0.5*mu*lambda*t075*(1.0 - 2.0*mu/(3.0*M_PI)) - 0.25*sqr(lambda)*mu
                    - 0.375*lambda*mu2*(1.0 + 3.33*mu) - a0*(b_1/6.0 - 0.25*a0*mu)
                    - qw*(a0/6.0 + mu*b_1/16.0) - pw*(t075/6.0 + 0.5*lambda + mu*a_1/16.0) );
    J_side = r1 * ( a0*(a_1*(1.0/6.0 - mu2) - 1.5*mu*(lambda + 0.5*t075))
                    + b_1*(t075/3.0*(1.0 + 1.5*mu2) + 0.75*lambda + 0.25*mu*a_1)
                    + qw*(t075/6.0 + 0.5*lambda + 7.0/16.0*mu*a_1) - pw*(a0/6.0 - 5.0/16.0*mu*b_1) );
  }
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "in-plane forces")
set(_old [=[                     - (Thrust*lambda + H_drag*mu)*Radius;
]=])
set(_new [=[                     - (Thrust*lambda + H_drag*mu)*Radius;

  // flightsim patch: the classical torque, TM-73254 eq. 4
  if (ClassicalModel) {
    const double t075 = theta_0 + 0.75 * BladeTwist, mu2 = sqr(mu);
    const double r9 = BladeNum*BladeChord*Radius*rho*sqr(Omega*Radius) * LiftCurveSlope/2.0 * Radius;
    Torque = r9 * ( delta_dr*(1.0 + mu2)/(4.0*LiftCurveSlope) - lambda*t075/3.0 - 0.5*sqr(lambda)
                    - (sqr(a_1) + sqr(b_1))/8.0 - 0.5*mu2*(0.5*sqr(a0) + 0.375*sqr(a_1) + sqr(b_1)/8.0)
                    - 0.5*mu*lambda*a_1 + mu*a0*b_1/3.0 );
  }
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "torque")
set(_old [=[    filtered_hagl = damp_hagl.execute(h_agl_ft) + GroundEffectShift;
]=])
set(_new [=[    if (FreshStart) { // flightsim patch: the filter starts at the height
      damp_hagl = Filter(1.0, dt);
      for (int i = 0; i < 4000; ++i) damp_hagl.execute(h_agl_ft);
    }
    filtered_hagl = damp_hagl.execute(h_agl_ft) + GroundEffectShift;
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "height filter")
set(_old [=[  avFus_ca = fus_angvel_body2ca(in.AeroPQR);

  calc_flow_and_thrust(theta_col, vHub_ca(eU), vHub_ca(eW), ge_factor);
]=])
set(_new [=[  avFus_ca = fus_angvel_body2ca(in.AeroPQR);
  p_w = avFus_ca(eP); // flightsim patch
  q_w = avFus_ca(eQ);

  // flightsim patch: a start converges the inflow from a typical rotor's; each
  // update is the lagged one, so its steady state is the one running reaches
  if (FreshStart) {
    FreshStart = false;
    nu = 0.05;
    lambda = vHub_ca(eW)/(Omega*Radius) - nu;
    for (int i = 0; i < 400; ++i)
      calc_flow_and_thrust(theta_col, vHub_ca(eU), vHub_ca(eW), ge_factor);
  }

  calc_flow_and_thrust(theta_col, vHub_ca(eU), vHub_ca(eW), ge_factor);
]=])
_fsim_jsbsim_edit(_text _old _new FGRotor.cpp "start")
_fsim_jsbsim_write(models/propulsion/FGRotor.cpp _text Propulsion)

foreach(_includer FGEngine.cpp FGTurboProp.cpp)
    _fsim_jsbsim_read(models/propulsion/${_includer} _text)
    _fsim_jsbsim_write(models/propulsion/${_includer} _text Propulsion)
endforeach()
target_include_directories(Propulsion PRIVATE ${FSIM_JSBSIM_SOURCE_DIR}/src/models/propulsion) # their other headers

# ---------------------------------------------------------------------------
# models/propulsion/FGElectric.cpp: a power source that burns fuel.
#
# hangar's helicopters fly their turboshafts as one governed power source: an
# electric engine whose power the flight control system meters (docs/
# rotorcraft.md). Upstream's electric engine burns nothing, so they flew on
# no fuel at all. An engine file may now give <bsfc unit="LBS/HP*HR"> (as a
# piston engine's does): the engine then burns bsfc times its power from the
# tanks that feed it - JSBSim's fuel freeze and trim honoured, its fuel flow
# reported as any engine's - and gives no power once they are empty. Without
# one nothing changes: it burns nothing, and a tankless engine (a
# multirotor's motor, which JSBSim counts as starved) keeps its power. The
# consumption is kept in the base's SLFuelFlowMax, which an electric engine
# never used, so FGElectric.h - and every file including it - stays upstream's.
# ---------------------------------------------------------------------------
_fsim_jsbsim_read(models/propulsion/FGElectric.cpp _text)
set(_old [=[  if (el->FindElement("power"))
    PowerWatts = el->FindElementValueAsNumberConvertTo("power","WATTS");
]=])
set(_new [=[  if (el->FindElement("power"))
    PowerWatts = el->FindElementValueAsNumberConvertTo("power","WATTS");
  // flightsim patch: its specific fuel consumption, lb per hp per second (none: 0)
  if (el->FindElement("bsfc"))
    SLFuelFlowMax = el->FindElementValueAsNumberConvertTo("bsfc", "LBS/HP*HR") / 3600.0;
]=])
_fsim_jsbsim_edit(_text _old _new FGElectric.cpp "consumption")
set(_old [=[  HP = PowerWatts * in.ThrottlePos[EngineNumber] / hptowatts;
]=])
set(_new [=[  HP = PowerWatts * in.ThrottlePos[EngineNumber] / hptowatts;
  // flightsim patch: an engine that burns fuel gives no power once its tanks are empty
  if (SLFuelFlowMax > 0.0 && Starved) {
    HP = 0.0;
    FuelFlowRate = 0.0;
  }
]=])
_fsim_jsbsim_edit(_text _old _new FGElectric.cpp "starved")
set(_old [=[double FGElectric::CalcFuelNeed(void)
{
  return 0;
}
]=])
set(_new [=[double FGElectric::CalcFuelNeed(void)
{
  // flightsim patch: bsfc times the power (none: nothing, as upstream)
  FuelFlowRate = SLFuelFlowMax * HP;
  FuelExpended = FuelFlowRate * in.TotalDeltaT;
  if (!Starved) FuelUsedLbs += FuelExpended;
  return FuelExpended;
}
]=])
_fsim_jsbsim_edit(_text _old _new FGElectric.cpp "fuel need")
_fsim_jsbsim_write(models/propulsion/FGElectric.cpp _text Propulsion)

# ---------------------------------------------------------------------------
# models/FGAccelerations.cpp: an impact the step cannot resolve.
#
# A contact's normal force is a spring and a damper, evaluated as a step
# begins and applied for the whole step - one and a half times over, as the
# translational rate is integrated by Adams-Bashforth 2. An aircraft that
# strikes the ground faster than its contacts can take in a step is deep in
# it before they see it (a Crazyflie at 35 m/s moves 0.29 m a step, sixteen
# times its 18 mm legs), and the force they then apply sends its contact
# points back out several times faster than they came in: the ground adds
# energy. The Crazyflie was thrown back up at 80 m/s, tumbling, and its state
# overflowed a second later. Now, when the ground's forces would send a
# contact point back out faster than it came in, by more than 5 m/s, the step
# applies instead the forces that stop the contact points' approach - each no
# more than its gear's, none leaving the ground faster than 0.5 m/s - solved
# as JSBSim solves its friction (projected Gauss-Seidel), and bounds the
# friction by them: an inelastic impact. Otherwise nothing changes, bit for
# bit: the check only reads the step's forces.
# ---------------------------------------------------------------------------
_fsim_jsbsim_read(models/FGAccelerations.cpp _text)
set(_old [=[#include "input_output/FGLog.h"
]=])
set(_new [=[#include "input_output/FGLog.h"
#include "FGGroundReactions.h" // flightsim patch: the impact limit's
]=])
_fsim_jsbsim_edit(_text _old _new FGAccelerations.cpp "include")
set(_old [=[namespace JSBSim {
]=])
set(_new [=[namespace JSBSim {

// flightsim patch (cmake/JsbsimPatches.cmake): an impact the step cannot
// resolve. The ground's forces - each contact's spring and damper - are
// applied for the whole step from the state it begins with; when they would
// send a contact point back out of the ground faster than it came in, they
// add energy. The step then applies instead the forces that stop the contact
// points' approach (an inelastic impact), and bounds the friction by them.
namespace {

// How much faster than it came in the ground's forces may send a contact
// point back out in a step before they are taken to add energy. The contacts
// a step integrates stay well within it: a Crazyflie parked on its legs (whose
// springs and dampers are stiff for the step: it hops) reaches 0.4 m/s, one
// dropped on its back from 0.3 m 4 m/s; its strikes of 10 m/s and more, tens.
const double kImpactMargin = 5.0 / 0.3048; // ft/s
// How fast a contact point so limited may leave the ground: an airframe
// driven into it comes back up at a walk.
const double kImpactRecovery = 0.5 / 0.3048; // ft/s
// JSBSim's default rate integrators, which flightsim keeps: the translational
// rate's Adams-Bashforth 2 applies 1.5 times the step's acceleration (less
// half the last step's), the rotational rate's Euler the step's.
const double kTranslationalGain = 1.5;

// a contact point the ground pushes
struct ImpactPoint {
  FGColumnVector3 n;   // the ground's normal, body axes, out of the ground
  FGColumnVector3 r;   // where its gear's force acts, body axes from the CG (ft)
  double force;        // its gear's force along n (lbf)
  double lambda;       // the force the step applies (lbf)
  double free;         // its speed along n after the step, the ground's forces left out (ft/s)
  size_t first, count; // its friction's multipliers
};

void LimitImpact(FGFDMExec* fdm, FGAccelerations::Inputs& in, double dt, const FGColumnVector3& lastUVWidot,
                 FGColumnVector3& uvwdot, FGColumnVector3& uvwidot, FGColumnVector3& pqrdot,
                 FGColumnVector3& pqridot, FGColumnVector3& bodyAccel)
{
  vector<LagrangeMultiplier*>& multipliers = *in.MultipliersList;
  if (multipliers.empty() || dt <= 0.0 || fdm->GetTrimStatus()) return;

  // What the ground's forces do to the step's speed and rate. When no contact
  // point can gain the margin from them, whatever its approach, nothing more
  // is done: the usual case.
  const FGColumnVector3 dv = (kTranslationalGain * dt / in.Mass) * in.GroundForce;
  const FGColumnVector3 dw = dt * (in.Jinv * in.GroundMoment);
  double reach = 0.0;
  for (const LagrangeMultiplier* m : multipliers) reach = max(reach, DotProduct(m->LeverArm, m->LeverArm));
  if (dv.Magnitude() + dw.Magnitude() * sqrt(reach) <= kImpactMargin) return;

  // Each contact point the ground pushes: does it leave faster than it came
  // in? Each gear in contact registered its friction's multipliers in turn -
  // its roll and side friction (LMultiplier[ftRoll] and [ftSide], adjacent) or
  // its sliding friction alone - the first's lever arm the point its force
  // acts at.
  const FGColumnVector3 v = in.vUVW - in.Tec2b * in.TerrainVelocity;
  const FGColumnVector3 w = in.vPQR - in.Tec2b * in.TerrainAngularVel;
  const auto ground = fdm->GetGroundReactions();
  vector<ImpactPoint> points;
  bool over = false;
  size_t k = 0;
  for (int g = 0; g < ground->GetNumGearUnits(); ++g) {
    const auto gear = ground->GetGearUnit(g);
    if (!gear->GetWOW()) continue;
    if (k >= multipliers.size()) return; // not as registered: the step is left as it is
    const size_t count = k + 1 < multipliers.size() && multipliers[k + 1] == multipliers[k] + 1 ? 2 : 1;
    const FGForce& f = *gear;
    const FGColumnVector3 fb(f.GetBodyXForce(), f.GetBodyYForce(), f.GetBodyZForce());
    const double force = fb.Magnitude();
    if (force > 0.0) {
      ImpactPoint p;
      p.n = fb / force;
      p.r = multipliers[k]->LeverArm;
      p.force = p.lambda = force;
      p.free = 0.0;
      p.first = k;
      p.count = count;
      const double approach = -DotProduct(p.n, v + w * p.r);
      if (DotProduct(p.n, dv + dw * p.r) > 2.0 * max(approach, 0.0) + kImpactMargin) over = true;
      points.push_back(p);
    }
    k += count;
  }
  if (!over || k != multipliers.size()) return;

  // The forces that stop the points' approach in the step, none leaving
  // faster than kImpactRecovery, each no more than its gear's: a[i*n+j] is
  // the speed along n_i a unit force at j gives in the step.
  const size_t n = points.size();
  vector<double> a(n * n);
  for (size_t j = 0; j < n; ++j) {
    const FGColumnVector3 dvj = (kTranslationalGain * dt / in.Mass) * points[j].n;
    const FGColumnVector3 dwj = dt * (in.Jinv * (points[j].r * points[j].n));
    for (size_t i = 0; i < n; ++i) a[i * n + j] = DotProduct(points[i].n, dvj + dwj * points[i].r);
  }
  // the body's speed and rate after the step, as the integrators will make
  // them, and each point's speed along its normal without the ground's forces
  const FGColumnVector3 vNext = v + dt * (in.Ti2b * (kTranslationalGain * uvwidot - (kTranslationalGain - 1.0) * lastUVWidot));
  const FGColumnVector3 wNext = w + dt * pqridot;
  for (size_t i = 0; i < n; ++i) {
    double theirs = 0.0;
    for (size_t j = 0; j < n; ++j) theirs += a[i * n + j] * points[j].force;
    points[i].free = DotProduct(points[i].n, vNext + wNext * points[i].r) - theirs;
  }
  // projected Gauss-Seidel, from the gears' own forces down
  for (int iter = 0; iter < 100; ++iter) {
    double change = 0.0;
    for (size_t i = 0; i < n; ++i) {
      double speed = points[i].free;
      for (size_t j = 0; j < n; ++j) speed += a[i * n + j] * points[j].lambda;
      const double lambda = min(max(points[i].lambda + (kImpactRecovery - speed) / a[i * n + i], 0.0), points[i].force);
      change += fabs(lambda - points[i].lambda) * a[i * n + i];
      points[i].lambda = lambda;
    }
    if (change < 1e-6) break;
  }
  // what the step applies instead, and each gear's friction bounded by it
  FGColumnVector3 dF, dM;
  for (const ImpactPoint& p : points) {
    const FGColumnVector3 d = (p.lambda - p.force) * p.n;
    dF += d;
    dM += p.r * d;
    const double scale = p.lambda / p.force;
    for (size_t m = p.first; m < p.first + p.count; ++m) {
      multipliers[m]->Max *= scale;
      multipliers[m]->Min *= scale;
      multipliers[m]->value = min(max(multipliers[m]->value, multipliers[m]->Min), multipliers[m]->Max);
    }
  }
  const FGColumnVector3 accel = dF / in.Mass;
  const FGColumnVector3 alpha = in.Jinv * dM;
  bodyAccel += accel;
  uvwdot += accel;
  uvwidot += in.Tb2i * accel;
  pqrdot += alpha;
  pqridot += alpha;
  in.Force += dF;
  in.Moment += dM;
  in.GroundForce += dF;
  in.GroundMoment += dM;
}

} // namespace
]=])
_fsim_jsbsim_edit(_text _old _new FGAccelerations.cpp "the limit")
set(_old [=[  CalculatePQRdot();   // Angular rate derivative
  CalculateUVWdot();   // Translational rate derivative

  if (!FDMExec->GetHoldDown())
    CalculateFrictionForces(in.DeltaT * rate);  // Update rate derivatives with friction forces
]=])
set(_new [=[  const FGColumnVector3 lastUVWidot = vUVWidot; // flightsim patch: the integrator's last, for LimitImpact
  CalculatePQRdot();   // Angular rate derivative
  CalculateUVWdot();   // Translational rate derivative

  if (!FDMExec->GetHoldDown()) {
    // flightsim patch: an impact the step cannot resolve
    LimitImpact(FDMExec, in, in.DeltaT * rate, lastUVWidot, vUVWdot, vUVWidot, vPQRdot, vPQRidot, vBodyAccel);
    CalculateFrictionForces(in.DeltaT * rate);  // Update rate derivatives with friction forces
  }
]=])
_fsim_jsbsim_edit(_text _old _new FGAccelerations.cpp "the call")
_fsim_jsbsim_write(models/FGAccelerations.cpp _text Models)
