# Fixes to JSBSim that flightsim carries.
#
# The submodule stays exactly as upstream ships it. Each fixed file is
# generated into the build tree - the upstream source with the edits below,
# each marked "flightsim patch" in the code - and compiled in place of the
# original (JSBSim is LGPL-2.1; see THIRD_PARTY_NOTICES.md). Every edit names
# the exact text it replaces: if upstream JSBSim no longer has it, configuring
# stops, so the fix is reviewed rather than silently lost.

set(_fsim_jsbsim_patched ${CMAKE_BINARY_DIR}/third_party/jsbsim-patched)

# Replace the one occurrence of the text in variable `old_var` with the text in
# `new_var`, inside variable `text_var`.
function(_fsim_jsbsim_edit text_var old_var new_var file what)
    string(FIND "${${text_var}}" "${${old_var}}" _at)
    if(_at EQUAL -1)
        message(FATAL_ERROR "JSBSim fix '${what}' no longer applies to ${file}: upstream changed it. "
                            "Review cmake/JsbsimPatches.cmake.")
    endif()
    string(REPLACE "${${old_var}}" "${${new_var}}" _text "${${text_var}}")
    set(${text_var} "${_text}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------------------
# models/FGLGear.cpp: a wheel on its side.
#
# A wheel's (BOGEY) strut is projected on the ground normal three times: its
# compression and compression speed are divided by the cosine of the strut's
# angle to the normal, and so is the ground force. As the strut turns towards
# the ground plane - a wheel meeting the ground sideways, as in a cartwheel -
# the force grows as 1/cos^2 without bound (0/0, NaN, with the strut parallel
# to the ground), and the aircraft is thrown back into the air or blows up:
# the stock c172x reached 9600 m/s. The projection is bounded at 45 degrees,
# so nothing changes while a strut is within 45 degrees of the ground normal.
# ---------------------------------------------------------------------------
set(_src ${FSIM_JSBSIM_SOURCE_DIR}/src/models/FGLGear.cpp)
file(READ ${_src} _text)
string(REPLACE "\r\n" "\n" _text "${_text}")

set(_old [=[namespace JSBSim {
]=])
set(_new [=[namespace JSBSim {

// flightsim patch (cmake/JsbsimPatches.cmake): the smallest projection of a
// wheel's strut on the ground normal used to turn its compression and force
// into the ground's frame - cos(45 deg). Below it, dividing by the projection
// made the ground force grow without bound as a wheel met the ground sideways.
static const double kMinStrutProjection = 0.70710678118654752;
]=])
_fsim_jsbsim_edit(_text _old _new ${_src} "the bound")

set(_old [=[      LGearProj = -(mTGear.Transposed() * vGroundNormal)(eZ);
]=])
set(_new [=[      LGearProj = -(mTGear.Transposed() * vGroundNormal)(eZ);
      // flightsim patch: bounded, see kMinStrutProjection
      if (LGearProj > 0.0) LGearProj = max(LGearProj, kMinStrutProjection);
]=])
_fsim_jsbsim_edit(_text _old _new ${_src} "compression")

set(_old [=[        if (eContactType == ctBOGEY)
          compressSpeed /= LGearProj;
]=])
set(_new [=[        if (eContactType == ctBOGEY) // flightsim patch: no 0/0 with the strut along the ground
          compressSpeed = LGearProj > 0.0 ? compressSpeed / LGearProj : 0.0;
]=])
_fsim_jsbsim_edit(_text _old _new ${_src} "compression speed")

set(_old [=[    vFn(eZ) = StrutForce / (mTGear.Transposed()*vGroundNormal)(eZ);
]=])
set(_new [=[    // flightsim patch: the projection bounded as for the compression; a
    // strut pointing away from the ground pushes on nothing
    {
      const double proj = (mTGear.Transposed()*vGroundNormal)(eZ);
      vFn(eZ) = proj < 0.0 ? StrutForce / min(proj, -kMinStrutProjection) : 0.0;
    }
]=])
_fsim_jsbsim_edit(_text _old _new ${_src} "ground force")

set(_dst ${_fsim_jsbsim_patched}/models/FGLGear.cpp)
file(WRITE ${_dst}.new "// Generated by flightsim from JSBSim's src/models/FGLGear.cpp with the fixes\n"
                       "// in cmake/JsbsimPatches.cmake (marked \"flightsim patch\"). Do not edit.\n${_text}")
configure_file(${_dst}.new ${_dst} COPYONLY) # rewritten only when it changes: no needless rebuilds
file(REMOVE ${_dst}.new)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_src})

get_target_property(_srcs Models SOURCES)
list(TRANSFORM _srcs REPLACE "(^|.*/)FGLGear\\.cpp$" "${_dst}")
set_property(TARGET Models PROPERTY SOURCES ${_srcs})
target_include_directories(Models PRIVATE ${FSIM_JSBSIM_SOURCE_DIR}/src/models) # its #include "FGLGear.h"
